import {
  spfOne,
  spfThree,
  spfFour,
  spfTwo,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/slim-threads/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/slim-threads/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/slim-threads/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "/slim-threads/contact",
  },
  // {
  //   _id: 1005,
  //   title: "Journal",
  //   link: "/journal",
  // },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: 9001,
    img: spfOne,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 9002,
    img: spfThree,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 9003,
    img: spfTwo,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 9004,
    img: spfFour,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: spfThree,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: spfFour,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Hoodie",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Shirts",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 10132510,
    img: newArrTwo,
    productName: "Shirts",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 10131230,
    img: newArrThree,
    productName: "Pullover",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 101312321,
    img: newArrFour,
    productName: "Pullover",
    oldPrice: "24.99",
    price: "17.99",
    color: "Male/Female - All Colors Available",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== PaginationItems End here =================
